spring:
  config:
    import: credentials.yml
    location: classpath:credentials.yml
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.naver.com # SMTP 서버 주소
    port: 465 # 메일 인증서버 포트
    username: ${email.admin.id}
    password: ${email.admin.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          connectiontimeout: 600000 # 600*1000
          ssl:
            trust: smtp.naver.com
            enable: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1

  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    data:
      mongodb:
        uri: mongodb://localhost:27017/just
server:
  port: 8081
